---
- name: install pip
  sudo: yes
  yum: name=python-pip

- name: install aws client
  sudo: yes
  pip: name=awscli

- name: create .aws directory
  sudo: yes
  file: dest="{{ GOCD_USER_HOME }}/.aws"
        state=directory
        owner="{{ GOCD_USER }}"
        group="{{ GOCD_GROUP }}"

- name: Copy .aws/config file
  template: "src=aws-config dest={{ GOCD_USER_HOME }}/.aws/config mode=0400 owner={{ GOCD_USER }} group={{ GOCD_GROUP }}"
