---
- name: yum install go-server
  sudo: yes
  yum: pkg=go-server-{{ GOCD_GO_VERSION }} state=present
  notify:
  - restart go-server
  when: ansible_pkg_mgr=='yum'

- name: apt install go-server
  sudo: yes
  apt: pkg=go-server={{ GOCD_GO_VERSION }} state=present force=yes
  when: ansible_pkg_mgr=='apt'
  notify:
  - restart go-server

- name: configure go-server
  lineinfile: dest=/etc/default/go-server  line="export JAVA_HOME={{ GOCD_JAVA_HOME}}"

- name: start go-server
  sudo: yes
  service: name=go-server state=started
  notify:
     - ensure go-server running

- name: check if firewalld is installed
  sudo: yes
  command: which firewalld
  ignore_errors: true
  register: firewalld

- name: check if firewalld service is running
  command: firewall-cmd --state
  sudo: yes
  when: firewalld|success
  register: firewalld_svc
  ignore_errors: true

- name: enable Go HTTP traffic through firewalld
  sudo: yes
  firewalld: port=8153/tcp permanent=true state=enabled
  when: firewalld|success and firewalld_svc.stdout=='running'
  notify:
    - restart firewalld

- name: enable Go HTTPS traffic through firewalld
  sudo: yes
  firewalld: port=8154/tcp permanent=true state=enabled
  when: firewalld|success and firewalld_svc.stdout=='running'
  notify:
    - restart firewalld

- name: check if UFW is available
  command: which ufw
  ignore_errors: true
  register: ufw

- name: enable Go HTTP traffic through ufw
  sudo: yes
  ufw: rule=allow port=8153 proto=tcp
  when: ufw|success

- name: enable Go HTTPS traffic through ufw
  sudo: yes
  ufw: rule=allow port=8154 proto=tcp
  when: ufw|success

- name: get iptables rules
  shell: /sbin/iptables -L
  register: iptablesrules
  always_run: yes
  sudo: yes

- name: add iptables rules for GoCD
  sudo: yes
  command: /sbin/iptables -I INPUT -p tcp --dport {{GOCD_SERVER_PORT}} -j ACCEPT -m comment --comment "gocd"
  when: iptablesrules.stdout.find("gocd") == -1
  notify:
    - iptables changed

- name: add iptables rules for GoCD (https)
  sudo: yes
  command: /sbin/iptables -I INPUT -p tcp --dport {{GOCD_SERVER_TLS_PORT}} -j ACCEPT -m comment --comment "gocd (https)"
  when: iptablesrules.stdout.find("gocd (https)") == -1
  notify:
    - iptables changed
