---
- name: ensure there is an m2 directory
  file: "state=directory path={{ GOCD_USER_HOME}}/.m2 owner={{ GOCD_USER }} group={{ GOCD_GROUP }}"

- name: Copy Maven settings.xml file
  template: "src=maven-settings.xml dest={{ GOCD_USER_HOME }}/.m2/settings.xml mode=0600 owner={{ GOCD_USER }} group={{ GOCD_GROUP }}"

